spring:
  application:
    name: restapi
  logging:
    level:
      root: INFO
      com.tr4.db.restapi: INFO
  cloud:
    gcp:
      project-id: tr4-2024-06-deutschebank
      credentials:
        location:
booking:
  event:
    topic: "booking-test"
