spring:
  application:
    name: restapi
  logging:
    level:
      root: INFO
      com.tr4.db.restapi: INFO
  cloud:
    gcp:
      project_id: tr4-2024-06-deutschebank
      credentials:
        location:
